name: Push Testing

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - uses: actions/checkout@v1
      - name: Install EPEL
        run: dnf install -y epel-release
      - name: Install dependencies
        run: dnf install -y python3 python3-m2crypto
      - name: Setup virtualenv
        run: |
          python3 -m venv --system-site-packages venv
          (. venv/bin/activate && pip install --upgrade pip wheel setuptools)
      - name: Install pdm from push
        run: (. venv/bin/activate && pip install -e .)
      - name: Install Tox and dependencies (for testing)
        run: (. venv/bin/activate && pip install tox)
      - name: Run tox testing
        run: (. venv/bin/activate && tox -e lint test)    

  unit:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - uses: actions/checkout@v1
      - name: Install EPEL
        run: dnf install -y epel-release
      - name: Install dependencies
        run: dnf install -y python3 python3-m2crypto
      - name: Setup virtualenv
        run: |
          python3 -m venv --system-site-packages venv
          (. venv/bin/activate && pip install --upgrade pip wheel setuptools)
      - name: Install pdm from push
        run: (. venv/bin/activate && pip install -e .)
      - name: Install Tox and dependencies (for testing)
        run: (. venv/bin/activate && pip install tox)
      - name: Run tox testing
        run: (. venv/bin/activate && tox -e unit test)

  full:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - uses: actions/checkout@v1
      - name: Install EPEL
        run: dnf install -y epel-release
      - name: Install dependencies
        run: dnf install -y openssl python3 python3-m2crypto python3-pyOpenSSL
      - name: Setup virtualenv
        run: |
          python3 -m venv --system-site-packages venv
          (. venv/bin/activate && pip install --upgrade pip wheel setuptools)
      - name: Install pdm from push
        run: (. venv/bin/activate && pip install -e .)
      - name: Install Tox and dependencies (for testing)
        run: (. venv/bin/activate && pip install tox)
      - name: Run tox testing
        run: (. venv/bin/activate && tox -e full test)
