name: Tox Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get install python python-pip python-virtualenv
          sudo apt-get install libssl-dev python-m2crypto
      - name: Setup virtualenv
        run: |
          virtualenv --system-site-packages venv
          (. venv/bin/activate && pip install --upgrade pip wheel setuptools)
      - name: Install pdm from push
        run: (. venv/bin/activate && pip install --user -e .)
      - name: Install Tox and dependencies (for testing)
        run: (. venv/bin/activate && pip install tox)
      - name: Run tox testing
        run: (. venv/bin/activate && tox -e ALL test)
